server:
  port: 8090

  # 防止乱码
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8


spring:
  application:
    name: SAA-10Text2voice

  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}