server:
  port: 8091

  # 防止乱码
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8


spring:
  application:
    name: SAA-11Embed2vector
  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      chroma:
        initialize-schema: true
        collection-name: spring-ai-demo
        client:
          host: http://192.168.114.128
          port: 8000
        tenant-name: SpringAiTenant
        database-name: SpringAiDatabase
#          username:
#          password:
#          key-token:

